name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
  push:
    tags-ignore:
      - "v*"
    branches:
      - "**"

jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        scala: [ 3.2.1 ]
        java: [ graalvm-ce-java17@22.3.0 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check commit message for breaking changes
        id: breaking-commit-message
        run: |
          COMMIT_MSG=$(git log --format=%B -n 1)
          echo "$COMMIT_MSG" | grep -qE "\[breaking\]" && echo "BREAKING=true" >> $GITHUB_OUTPUT || echo "BREAKING=false" >> $GITHUB_OUTPUT
        continue-on-error: true
      - name: Compile and test
        run: sbt +test scalafmtCheckAll
      - name: MiMa check
        if: steps.breaking-commit-message.outputs.BREAKING != 'true'
        run: sbt +mimaReportBinaryIssues
