name: Test

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - "v*"
    branches:
      - "**"

jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        scala: [ 3.2.1 ]
        java: [ graalvm-ce-java17@22.3.0 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Compile and test
        run: sbt +test scalafmtCheckAll
