name: Test

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - "*"
    branches:
      - "*"
  pull_request:

jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        scala: [ 3.1.3 ]
        java: [ graalvm-ce-java17@22.2.0 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Compile and test
        run: sbt +test scalafmtCheckAll
